backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "producten"
    label: "Producten"
    folder: "content/producten"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
      - {label: "Prijs", name: "price", widget: "number"}
      - {label: "Omschrijving", name: "description", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image"}