backend:
  name: github
  repo: timdekruyf07-dotcom/website-kaars
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "producten"
    label: "Producten"
    folder: "content/producten"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Prijs", name: "price", widget: "number"}
      - {label: "Beschrijving", name: "description", widget: "text"}
      - {label: "Afbeelding", name: "image", widget: "image"}
